# Generated by Django 6.1.1 on 2026-09-17 10:22

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120, verbose_name='brand')),
                ('bought_price', models.PositiveIntegerField(verbose_name='bought price')),
                ('picture', models.ImageField(blank=True, upload_to='batches/%Y/%m/', verbose_name='picture')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date added')),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='SizeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=inventory.models.generate_code, editable=False, max_length=16, unique=True, verbose_name='code')),
                ('size', models.CharField(max_length=10, verbose_name='size')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('initial_quantity', models.PositiveIntegerField(verbose_name='initial quantity')),
                ('label_printed', models.BooleanField(default=False, verbose_name='label printed')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='inventory.batch', verbose_name='batch')),
            ],
            options={
                'verbose_name': 'size entry',
                'verbose_name_plural': 'size entries',
                'ordering': ['-batch__date_added', 'size'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.PositiveIntegerField(verbose_name='sold price')),
                ('sold_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='sold at')),
                ('size_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.sizeentry', verbose_name='size entry')),
            ],
            options={
                'verbose_name': 'sale',
                'verbose_name_plural': 'sales',
                'ordering': ['-sold_at'],
            },
        ),
    ]
