# Generated by Django 6.1.1 on 2026-09-17 10:32

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='picture',
            field=models.ImageField(blank=True, upload_to=inventory.models.picture_path, verbose_name='picture'),
        ),
    ]
