# Generated by Django 6.1.1 on 2026-09-17 13:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill(apps, schema_editor):
    # Before this log existed, top-ups weren't dated; record each line's total as received on its batch date.
    SizeEntry = apps.get_model('inventory', 'SizeEntry')
    Restock = apps.get_model('inventory', 'Restock')
    Restock.objects.bulk_create(
        Restock(size_entry_id=entry.pk, quantity=entry.initial_quantity, received_at=entry.batch.date_added)
        for entry in SizeEntry.objects.select_related('batch').filter(initial_quantity__gt=0)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_batch_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='received at')),
                ('size_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='inventory.sizeentry', verbose_name='size entry')),
            ],
            options={
                'verbose_name': 'restock',
                'verbose_name_plural': 'restocks',
                'ordering': ['-received_at'],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
]
