# Generated by Django 6.1.1 on 2026-09-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_restock_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='cash', max_length=4, verbose_name='payment'),
        ),
    ]
